# Generated by Django 4.2.30 on 2026-06-11 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=160)),
                ('video', models.FileField(upload_to='videos/')),
                ('first_frame', models.FileField(blank=True, upload_to='frames/')),
                ('frame_width', models.PositiveIntegerField(default=0)),
                ('frame_height', models.PositiveIntegerField(default=0)),
                ('fps', models.FloatField(default=0)),
                ('total_frames', models.PositiveIntegerField(default=0)),
                ('zones', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('ready', 'Listo'), ('running', 'Analizando'), ('completed', 'Completado'), ('failed', 'Fallido'), ('canceled', 'Cancelado')], default='draft', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('processed_frames', models.PositiveIntegerField(default=0)),
                ('confirmed_people', models.PositiveIntegerField(default=0)),
                ('status_message', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('output_dir', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
