# Generated by Django 4.2.30 on 2026-06-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='area',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=140),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='mall',
            field=models.CharField(blank=True, db_index=True, max_length=140),
        ),
    ]
