# Generated by Django 4.2.30 on 2026-06-11 05:17

from django.db import migrations, models
import django.db.models.deletion


def link_existing_malls(apps, schema_editor):
    AnalysisRun = apps.get_model('analytics', 'AnalysisRun')
    Mall = apps.get_model('analytics', 'Mall')

    for analysis in AnalysisRun.objects.exclude(mall="").iterator():
        mall_name = (analysis.mall or "").strip()
        if not mall_name:
            continue
        mall_group, _ = Mall.objects.get_or_create(name=mall_name)
        analysis.mall_group = mall_group
        analysis.save(update_fields=["mall_group"])


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_analysisrun_area_analysisrun_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='mall_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='analytics.mall'),
        ),
        migrations.RunPython(link_existing_malls, migrations.RunPython.noop),
    ]
