# Generated by Django 4.2.30 on 2026-06-11 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_mall_analysisrun_mall_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='mall',
            name='accent_color',
            field=models.CharField(default='#32D583', max_length=7),
        ),
        migrations.AddField(
            model_name='mall',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
