# Generated by Django 4.2.30 on 2026-06-25 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0004_mall_accent_color_mall_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('upload', 'Carga de video'), ('zones_save', 'Guardado de zonas'), ('run_start', 'Inicio de analisis'), ('run_cancel', 'Cancelacion'), ('report_download', 'Descarga de reporte'), ('executive_export', 'Exportacion ejecutiva'), ('note_save', 'Nota de insight'), ('move', 'Asignacion'), ('rename', 'Renombrado'), ('unassign', 'Desasignacion'), ('delete', 'Eliminacion'), ('mall_change', 'Cambio de establecimiento')], max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='analytics.analysisrun')),
                ('mall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='analytics.mall')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZoneVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('zones', models.JSONField(default=list)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_versions', to='analytics.analysisrun')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zone_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('analysis', 'version')},
            },
        ),
        migrations.CreateModel(
            name='InsightNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_key', models.CharField(db_index=True, max_length=80)),
                ('body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insight_notes', to='analytics.analysisrun')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insight_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['insight_key'],
                'unique_together': {('analysis', 'insight_key')},
            },
        ),
    ]
