# Generated by Django 4.2.30 on 2026-06-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_analysisauditlog_zoneversion_insightnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openai_api_key', models.CharField(blank=True, max_length=255)),
                ('openai_model', models.CharField(default='gpt-4o-mini', max_length=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracion',
                'verbose_name_plural': 'Configuracion',
            },
        ),
    ]
