# Generated by Django 4.2.30 on 2026-06-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_appconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='analysis_type',
            field=models.CharField(choices=[('pedestrian', 'Establecimiento peatonal'), ('parking', 'Estacionamiento')], db_index=True, default='pedestrian', max_length=20),
        ),
    ]
